In [3]:
!pip install tensorflow==2.9.1 tensorflow-gpu==2.9.1 opencv-python matplotlib

In [2]:
import tensorflow as tf
import numpy as np
from matplotlib import pyplot as plt
import cv2

### Load Model

In [3]:
interpreter = tf.lite.Interpreter(model_path='lite-model_movenet_singlepose_thunder_tflite_float16_4.tflite')
interpreter.allocate_tensors()

### Make Detection

In [13]:
cap = cv2.VideoCapture(0)
while cap.isOpened():
    ret, frame = cap.read()
    
    # reshape image
    img = frame.copy()
    img = tf.image.resize_with_pad(np.expand_dims(img, axis=0),256, 256)
    input_image = tf.cast(img, dtype=tf.uint8)
    
    # setup input and output
    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()
    
    # make prediction
    interpreter.set_tensor(input_details[0]['index'], input_image.numpy())
    interpreter.invoke()
    keypoints_with_scores = interpreter.get_tensor(output_details[0]['index'])
    print(keypoints_with_scores)
    
    # rendering
    draw_keypoints(frame, keypoints_with_scores, 0.4)
    draw_edges(frame, keypoints_with_scores, EDGES, 0.4)
    
    cv2.imshow('MoveNet Thunder', frame)
    if cv2.waitKey(10) & 0xFF==ord('q'):
        break
        
cap.release()
cv2.destroyAllWindows()

[[[[0.7216342  0.58934045 0.5318955 ]
   [0.6522581  0.65201604 0.7322948 ]
   [0.65263605 0.52376235 0.6591982 ]
   [0.61890393 0.7184306  0.720888  ]
   [0.61229444 0.43864307 0.47974724]
   [0.8078293  0.77709424 0.5569226 ]
   [0.7913022  0.31893343 0.60217977]
   [0.8663936  0.82149833 0.13581827]
   [0.85622096 0.26868662 0.02752538]
   [0.8654165  0.8268424  0.08458904]
   [0.8475827  0.279567   0.01893401]
   [1.0275589  0.6948803  0.04150128]
   [0.893512   0.32334664 0.04184927]
   [0.86115205 0.80669487 0.07509188]
   [0.80945927 0.30816722 0.08005059]
   [0.8594635  0.76385975 0.02111189]
   [0.86767185 0.8209299  0.024359  ]]]]
[[[[0.74188846 0.5794454  0.47743466]
   [0.67129856 0.64524376 0.7538998 ]
   [0.66696167 0.51591796 0.5617039 ]
   [0.6277996  0.7191422  0.60935974]
   [0.61922014 0.43595338 0.5729594 ]
   [0.80395013 0.77091026 0.6288221 ]
   [0.7958286  0.3167288  0.67944956]
   [0.8647825  0.8084694  0.16349904]
   [0.8684243  0.2361216  0.04761839]
   [0.989

[[[[0.63323414 0.5378728  0.5996312 ]
   [0.5737186  0.59746945 0.63893247]
   [0.57479715 0.4870245  0.67131865]
   [0.5793882  0.6590806  0.6519277 ]
   [0.57994485 0.41777396 0.44328794]
   [0.79763645 0.7510545  0.60719275]
   [0.78585476 0.30695423 0.6641842 ]
   [0.9774606  0.82812995 0.05079326]
   [0.85566795 0.00200361 0.02693536]
   [0.86919606 0.6357248  0.02051967]
   [0.5871123  0.04824837 0.02793769]
   [1.0353209  0.60547733 0.03348755]
   [0.9618817  0.31661513 0.0463219 ]
   [0.861703   0.792649   0.08780435]
   [0.8448662  0.29285875 0.06218057]
   [0.7431858  0.60017025 0.02958006]
   [0.7806599  0.7423493  0.00687608]]]]
[[[[0.63132685 0.53697467 0.6181152 ]
   [0.57018137 0.59517354 0.5639435 ]
   [0.5714751  0.4875796  0.70103896]
   [0.57684803 0.65666366 0.5994214 ]
   [0.5769571  0.4182979  0.476906  ]
   [0.79305065 0.7473257  0.5959661 ]
   [0.7853426  0.30184236 0.7417485 ]
   [0.9774521  0.82902634 0.04896967]
   [0.8603276  0.00324353 0.02884186]
   [0.868

[[[[0.6085371  0.69178975 0.501783  ]
   [0.52924585 0.76185834 0.5667994 ]
   [0.51880646 0.61805737 0.7059053 ]
   [0.52940035 0.83923477 0.6417942 ]
   [0.51676834 0.51982135 0.6191848 ]
   [0.7543509  0.88179153 0.42167595]
   [0.72714835 0.36847472 0.6598854 ]
   [0.8555809  0.98778284 0.07475433]
   [0.87289727 0.23400839 0.08398695]
   [0.8553932  0.7975554  0.02611513]
   [0.71580154 0.36751905 0.00300869]
   [1.0392728  0.7821639  0.02968858]
   [0.95828426 0.41833848 0.05662118]
   [0.8204603  0.9544311  0.03582635]
   [0.74108785 0.35401618 0.06275897]
   [0.74094206 0.84663177 0.03417681]
   [0.78971714 0.8575568  0.01123179]]]]
[[[[0.6124733  0.6794635  0.37815198]
   [0.52784795 0.75328547 0.6564596 ]
   [0.51755786 0.6064576  0.66329646]
   [0.52798915 0.83189154 0.67463577]
   [0.50562865 0.513715   0.47833183]
   [0.77500635 0.8939066  0.46745837]
   [0.7314303  0.3606714  0.65749717]
   [0.8561125  0.9847017  0.08569492]
   [0.87594056 0.22849801 0.09288903]
   [0.849

[[[[0.40311816 0.61226594 0.20266221]
   [0.34195963 0.6839593  0.20172901]
   [0.34579483 0.5591308  0.14503226]
   [0.35508814 0.7743043  0.2148903 ]
   [0.37073207 0.45906404 0.31281912]
   [0.6962289  0.8661866  0.50575924]
   [0.6233659  0.26296735 0.7516782 ]
   [0.65069485 0.8217474  0.02800312]
   [0.97856927 0.01214147 0.08912378]
   [0.5647775  0.6702693  0.03135122]
   [0.17572136 0.54422337 0.06207098]
   [0.8036675  0.6871792  0.02618559]
   [0.8794742  0.3108946  0.06093659]
   [0.6651565  0.8424411  0.11861938]
   [0.7089763  0.567341   0.14117175]
   [0.7311414  0.7794702  0.03846697]
   [0.7927192  0.63230675 0.01482153]]]]
[[[[0.24906048 0.5938481  0.454091  ]
   [0.19027068 0.65802467 0.51821256]
   [0.17787516 0.5155568  0.5433819 ]
   [0.2284913  0.7434642  0.44626153]
   [0.21678105 0.43240896 0.40778556]
   [0.52531576 0.8426864  0.8448006 ]
   [0.49809262 0.26844347 0.802433  ]
   [0.8460999  0.9999211  0.1699962 ]
   [0.85572684 0.07203086 0.7370958 ]
   [0.868

[[[[0.3068468  0.7228104  0.77831554]
   [0.2747954  0.75071985 0.7471365 ]
   [0.28335667 0.6883453  0.7218443 ]
   [0.28812242 0.7950029  0.6732048 ]
   [0.3127698  0.65474033 0.7407694 ]
   [0.4025235  0.913522   0.8419767 ]
   [0.4703369  0.62758595 0.90060693]
   [0.6131178  0.98007256 0.09242102]
   [0.6958669  0.5562855  0.6536331 ]
   [0.7307738  0.9740601  0.09408084]
   [0.86324763 0.4789453  0.41540825]
   [0.8464911  0.9589276  0.7263763 ]
   [0.8628609  0.758209   0.78323495]
   [0.84685063 0.9784373  0.03850206]
   [0.85516644 0.7448877  0.06128676]
   [0.86053747 0.8885162  0.0450098 ]
   [0.8624148  0.8830618  0.0542866 ]]]]
[[[[0.3068468  0.7228104  0.77831554]
   [0.2747954  0.75071985 0.7471365 ]
   [0.28335667 0.6883453  0.7218443 ]
   [0.28812242 0.7950029  0.6732048 ]
   [0.3127698  0.65474033 0.7407694 ]
   [0.4025235  0.913522   0.8419767 ]
   [0.4703369  0.62758595 0.90060693]
   [0.6131178  0.98007256 0.09242102]
   [0.6958669  0.5562855  0.6536331 ]
   [0.730

[[[[0.41246167 0.6763024  0.7684406 ]
   [0.39135885 0.6955768  0.69843656]
   [0.39048618 0.65286726 0.66889405]
   [0.40385082 0.7179405  0.601164  ]
   [0.40547222 0.62106884 0.70108867]
   [0.51546854 0.78278863 0.8554495 ]
   [0.52300096 0.56978863 0.9054163 ]
   [0.6561719  0.8755695  0.8126737 ]
   [0.658112   0.51388085 0.8636054 ]
   [0.73791367 0.90746295 0.6656748 ]
   [0.76043093 0.47449255 0.86457527]
   [0.84714943 0.7618617  0.84459525]
   [0.843306   0.6141284  0.8105416 ]
   [0.85748833 0.88751125 0.13800049]
   [0.83348376 0.46495512 0.13218828]
   [0.8598346  0.7044854  0.02057969]
   [0.8549034  0.6945372  0.05230484]]]]
[[[[0.4154244  0.6842303  0.7585726 ]
   [0.39531103 0.70327294 0.6610333 ]
   [0.39530012 0.66233134 0.7999792 ]
   [0.4071456  0.7276726  0.7334422 ]
   [0.40860936 0.63311064 0.8116977 ]
   [0.5194142  0.7953631  0.9032085 ]
   [0.52303404 0.5811563  0.87531954]
   [0.6392775  0.8971336  0.640805  ]
   [0.6392565  0.52338237 0.7747497 ]
   [0.667

[[[[0.43083826 0.6846404  0.70238477]
   [0.4146285  0.7020613  0.49389598]
   [0.41226953 0.6637998  0.755672  ]
   [0.42316616 0.7272613  0.65679747]
   [0.42172346 0.6321907  0.6129527 ]
   [0.5308065  0.7844778  0.7292241 ]
   [0.5325953  0.58775365 0.78195775]
   [0.59884864 0.9330185  0.8478616 ]
   [0.6053791  0.48830333 0.82749736]
   [0.46090043 0.91485673 0.7220783 ]
   [0.47412243 0.49971974 0.6619626 ]
   [0.8434608  0.77363986 0.7309259 ]
   [0.8419701  0.624291   0.76585984]
   [0.8688439  0.9502455  0.12345696]
   [0.8615511  0.5407542  0.03921198]
   [0.8561593  0.8974741  0.02649103]
   [0.8532931  0.5460858  0.01935047]]]]
[[[[0.4333757  0.68579316 0.6149373 ]
   [0.41621014 0.70296353 0.5321239 ]
   [0.4143297  0.66395444 0.7905667 ]
   [0.4242792  0.72748005 0.7258688 ]
   [0.42335665 0.63220376 0.670141  ]
   [0.5299922  0.78708744 0.76376885]
   [0.5320171  0.5887293  0.6166593 ]
   [0.59117365 0.9363632  0.8239023 ]
   [0.6024113  0.4884915  0.81980306]
   [0.454

[[[[0.46147507 0.67047405 0.52778745]
   [0.44096774 0.68826187 0.5973667 ]
   [0.44244537 0.6525817  0.6419227 ]
   [0.4481598  0.7166672  0.67456174]
   [0.45227724 0.63131243 0.5403206 ]
   [0.5399572  0.77676564 0.7889803 ]
   [0.55066717 0.5972524  0.77825403]
   [0.6058123  0.9170176  0.72249186]
   [0.61244816 0.49390745 0.59126484]
   [0.47060588 0.89589703 0.66778255]
   [0.48587015 0.5142694  0.6296016 ]
   [0.84349924 0.7617466  0.7666409 ]
   [0.84123635 0.6234165  0.77565944]
   [0.86079806 0.94637537 0.19296488]
   [0.8583338  0.569052   0.02667347]
   [0.85327137 0.9279564  0.08376229]
   [0.8651885  0.71308213 0.0106267 ]]]]
[[[[0.46938157 0.6528612  0.355624  ]
   [0.4503617  0.6701618  0.3821553 ]
   [0.45410562 0.6358075  0.4591812 ]
   [0.45320252 0.6950551  0.45649928]
   [0.4613015  0.6199258  0.50807005]
   [0.55179346 0.76582366 0.66098833]
   [0.5578619  0.5934415  0.67967117]
   [0.6145587  0.89739335 0.6092428 ]
   [0.6152177  0.49151212 0.7344607 ]
   [0.492

[[[[0.4996779  0.6413334  0.37937075]
   [0.48226935 0.65407854 0.45978808]
   [0.4856504  0.62374437 0.429258  ]
   [0.48011005 0.68618566 0.5817915 ]
   [0.49124026 0.60635585 0.4579655 ]
   [0.5608669  0.7347198  0.581819  ]
   [0.5784069  0.59503955 0.60371864]
   [0.6169543  0.8587536  0.67800325]
   [0.6297316  0.5075919  0.6163579 ]
   [0.5129793  0.8171761  0.4351678 ]
   [0.5365006  0.5086224  0.56328547]
   [0.8374298  0.7271479  0.77603173]
   [0.8364664  0.61586195 0.7855279 ]
   [0.86684483 0.9354684  0.02663896]
   [0.8671088  0.59836227 0.00961934]
   [0.8499668  0.8939259  0.03728835]
   [0.85093576 0.90452534 0.01951173]]]]
[[[[0.49703985 0.6383795  0.55136716]
   [0.48153627 0.65325207 0.5250499 ]
   [0.48444793 0.62202245 0.39836842]
   [0.48645777 0.6832119  0.65437585]
   [0.49509037 0.6063129  0.5751196 ]
   [0.5692588  0.7299958  0.7738159 ]
   [0.5833691  0.5861271  0.75189954]
   [0.6278605  0.8461252  0.65067244]
   [0.62990373 0.49821475 0.65244544]
   [0.523

[[[[0.5242203  0.59912825 0.5905714 ]
   [0.51218426 0.61327654 0.55146825]
   [0.51166874 0.5877476  0.57505965]
   [0.5206566  0.63202435 0.6378426 ]
   [0.51945204 0.56581736 0.56182945]
   [0.59529877 0.66288847 0.58991075]
   [0.5949888  0.54065263 0.62392646]
   [0.64605635 0.75679946 0.5061581 ]
   [0.63720316 0.46458468 0.5034771 ]
   [0.554674   0.74932766 0.37109062]
   [0.53940016 0.48415107 0.41111168]
   [0.8152837  0.65782917 0.6308055 ]
   [0.82399833 0.56687164 0.693967  ]
   [0.87525046 0.67808133 0.01534905]
   [0.87414414 0.5750379  0.01013487]
   [0.8633067  0.6695094  0.0079253 ]
   [0.55933857 0.48255578 0.01405284]]]]
[[[[0.52731836 0.6093567  0.44041234]
   [0.515462   0.6220462  0.36570883]
   [0.5158118  0.59631926 0.4111623 ]
   [0.5225539  0.63883483 0.5824493 ]
   [0.52489674 0.5778687  0.5704122 ]
   [0.5935336  0.6698938  0.538243  ]
   [0.5992917  0.5439543  0.5584903 ]
   [0.6499424  0.7632721  0.45738205]
   [0.63648725 0.47437814 0.7389873 ]
   [0.552

[[[[0.5441156  0.57914567 0.43781173]
   [0.5288165  0.58258206 0.49908325]
   [0.53179246 0.5704748  0.4538944 ]
   [0.5313179  0.58366376 0.34471807]
   [0.5324652  0.55548745 0.4136257 ]
   [0.60488504 0.6076349  0.4337458 ]
   [0.60686475 0.5380928  0.4038791 ]
   [0.6493041  0.720184   0.3112679 ]
   [0.6488657  0.4404835  0.30303365]
   [0.5624828  0.71822137 0.18030263]
   [0.56147057 0.44966847 0.35395512]
   [0.8164005  0.6067994  0.4517227 ]
   [0.82321185 0.57864165 0.39776453]
   [0.87353754 0.66938984 0.06188066]
   [0.8731895  0.66645277 0.05649261]
   [0.7950543  0.5129517  0.0333198 ]
   [0.79874843 0.50925916 0.02840386]]]]
[[[[0.5425651  0.5564636  0.5181594 ]
   [0.53057796 0.5700364  0.4262719 ]
   [0.5281992  0.54407346 0.3557948 ]
   [0.53673166 0.58717734 0.608901  ]
   [0.5351978  0.5217857  0.5976249 ]
   [0.5970695  0.61521465 0.7106342 ]
   [0.61114264 0.48996994 0.65581644]
   [0.6492717  0.6945974  0.52841806]
   [0.64967453 0.41966087 0.47092944]
   [0.561

[[[[0.56825435 0.53364563 0.5021134 ]
   [0.5536478  0.54199237 0.589159  ]
   [0.5542288  0.5191056  0.561049  ]
   [0.5582644  0.55521727 0.4912419 ]
   [0.5615558  0.4969434  0.4271081 ]
   [0.6192938  0.5750109  0.48091385]
   [0.63812697 0.47672483 0.6922772 ]
   [0.6215257  0.6734246  0.45765716]
   [0.6487881  0.40263307 0.61840814]
   [0.53827375 0.64033484 0.56165713]
   [0.5574444  0.42434582 0.34909353]
   [0.789808   0.59874445 0.49927396]
   [0.81521016 0.539096   0.52735096]
   [0.7084086  0.68976974 0.5759979 ]
   [0.7723665  0.54651225 0.2317705 ]
   [0.79277515 0.84588724 0.43512985]
   [0.84565014 0.5669964  0.2655609 ]]]]
[[[[0.5675882  0.527124   0.58248127]
   [0.5551978  0.53652    0.6500542 ]
   [0.5550555  0.5148752  0.54752266]
   [0.55925035 0.54977673 0.4556703 ]
   [0.56204736 0.48916006 0.5207462 ]
   [0.6164897  0.57485014 0.7028437 ]
   [0.639094   0.47406703 0.72341835]
   [0.6231029  0.6695587  0.5639852 ]
   [0.6517599  0.40166247 0.5774062 ]
   [0.542

[[[[0.5736531  0.52932125 0.38289288]
   [0.5559795  0.5317702  0.49053472]
   [0.5569306  0.51538974 0.4741591 ]
   [0.559266   0.53463274 0.42092022]
   [0.5632158  0.49249956 0.45439532]
   [0.6172693  0.55825156 0.36103436]
   [0.63785505 0.4773287  0.636287  ]
   [0.6204077  0.66218    0.31990904]
   [0.65351295 0.4004382  0.44379175]
   [0.5463134  0.6447791  0.35822046]
   [0.5551683  0.42322156 0.37027583]
   [0.7916467  0.58952546 0.36585212]
   [0.8206068  0.5341937  0.5224335 ]
   [0.7172918  0.7209591  0.42287454]
   [0.7860613  0.59850055 0.09226055]
   [0.7902181  0.90934545 0.5080366 ]
   [0.85657245 0.66351664 0.04559366]]]]
[[[[0.5710831  0.53092784 0.36660165]
   [0.5542931  0.52944374 0.43425593]
   [0.5558523  0.51957154 0.5852149 ]
   [0.55676514 0.5250329  0.3017211 ]
   [0.56204736 0.5035761  0.40258518]
   [0.6162596  0.5473065  0.37258622]
   [0.6320178  0.48554525 0.477691  ]
   [0.6301427  0.6630703  0.3714898 ]
   [0.65280205 0.40065116 0.3887485 ]
   [0.547

[[[[0.5624224  0.56058395 0.3664014 ]
   [0.54833424 0.57092416 0.46223316]
   [0.54837435 0.54684293 0.3147625 ]
   [0.552785   0.57626444 0.37437743]
   [0.55287075 0.5179427  0.5679556 ]
   [0.62386066 0.59560776 0.47091103]
   [0.6196272  0.4830238  0.6923911 ]
   [0.65938276 0.68467337 0.45268255]
   [0.6068268  0.41824973 0.64543587]
   [0.5704777  0.7024039  0.5335916 ]
   [0.5218412  0.47269693 0.4639296 ]
   [0.7881974  0.59570205 0.4692658 ]
   [0.80783373 0.5360861  0.54603124]
   [0.71664345 0.70510244 0.476502  ]
   [0.7734628  0.53281564 0.21103874]
   [0.8287278  0.8814894  0.5424658 ]
   [0.8440665  0.5636428  0.18185899]]]]
[[[[0.5621688  0.5574723  0.45421687]
   [0.54885995 0.5717504  0.47676474]
   [0.54654294 0.5451008  0.3734059 ]
   [0.55365926 0.57920724 0.5049288 ]
   [0.55229974 0.5182096  0.6045822 ]
   [0.6235286  0.5972025  0.52247846]
   [0.6199224  0.48789576 0.7421582 ]
   [0.6643943  0.6865256  0.5473838 ]
   [0.6027659  0.42363486 0.7381031 ]
   [0.571

[[[[0.5232555  0.59876674 0.52816105]
   [0.51100355 0.6144529  0.6507195 ]
   [0.50834394 0.5852439  0.6405724 ]
   [0.52121997 0.631265   0.5793478 ]
   [0.5168673  0.5610601  0.37913662]
   [0.6023577  0.6495206  0.63372123]
   [0.5944186  0.5311858  0.49509066]
   [0.681564   0.7396353  0.5047381 ]
   [0.6223783  0.44808233 0.4107054 ]
   [0.61102986 0.73823136 0.20029432]
   [0.52113366 0.4802623  0.518541  ]
   [0.8276127  0.6520196  0.66256726]
   [0.84335583 0.553465   0.6750221 ]
   [0.8643993  0.6854233  0.04628275]
   [0.8617804  0.5502919  0.02045504]
   [0.8597613  0.95182145 0.07975225]
   [0.8635169  0.95186484 0.04297527]]]]
[[[[0.5191634  0.6064616  0.5476341 ]
   [0.50858235 0.6214956  0.5811138 ]
   [0.505051   0.5930305  0.44687107]
   [0.5195061  0.637753   0.5661416 ]
   [0.51298827 0.5678326  0.59556055]
   [0.6012896  0.65922755 0.7883651 ]
   [0.593391   0.5328036  0.6662006 ]
   [0.6899314  0.7388286  0.63439786]
   [0.6204036  0.44933    0.59762406]
   [0.635

[[[[0.40844542 0.64077497 0.5335319 ]
   [0.38211134 0.6658973  0.7618246 ]
   [0.38012052 0.6157356  0.77040666]
   [0.39215124 0.6928165  0.7537414 ]
   [0.39181298 0.577267   0.5797609 ]
   [0.49871096 0.7689667  0.8410072 ]
   [0.5355477  0.54035383 0.8693327 ]
   [0.6066577  0.92421263 0.7653121 ]
   [0.6988909  0.46066162 0.7871438 ]
   [0.48293146 0.9387028  0.7624046 ]
   [0.54269665 0.44832984 0.6897214 ]
   [0.84819573 0.8099082  0.8319477 ]
   [0.8495443  0.6337996  0.7044832 ]
   [0.868574   0.9324661  0.07846292]
   [0.8545508  0.4781228  0.06397276]
   [0.8448115  0.57881993 0.05468346]
   [0.8619846  0.72227144 0.02303438]]]]
[[[[0.39958772 0.64343804 0.700715  ]
   [0.37171367 0.6690561  0.47022262]
   [0.370486   0.61753154 0.73833346]
   [0.38173974 0.6959852  0.856762  ]
   [0.38334832 0.5774843  0.7026928 ]
   [0.489612   0.77216035 0.6782035 ]
   [0.5276968  0.5423701  0.88575107]
   [0.60955256 0.9256083  0.70441955]
   [0.68310285 0.45419365 0.89125335]
   [0.491

[[[[0.25170454 0.9508761  0.54732406]
   [0.21649358 0.98689896 0.5568658 ]
   [0.21287861 0.91061336 0.6680676 ]
   [0.23174572 1.0167454  0.11303919]
   [0.22430958 0.85343677 0.82365984]
   [0.41527995 0.9923447  0.1826425 ]
   [0.3531753  0.7244521  0.8016857 ]
   [0.6397273  0.96844184 0.2614782 ]
   [0.51530844 0.56283736 0.7769257 ]
   [0.7906209  0.9588842  0.18675667]
   [0.42452312 0.42917028 0.65848315]
   [0.8561116  0.9091094  0.61738133]
   [0.8433515  0.679788   0.62906456]
   [0.86445427 0.9620014  0.03448006]
   [0.8546104  0.6330128  0.05439809]
   [0.85679924 0.87394696 0.03286426]
   [1.0033453  0.7160905  0.01418745]]]]
[[[[0.24239899 0.92739993 0.55758893]
   [0.20604526 0.9717893  0.5670501 ]
   [0.20406726 0.88918406 0.62015134]
   [0.21876916 1.0084085  0.17195605]
   [0.21667622 0.8247781  0.5737617 ]
   [0.4234505  0.98995525 0.21937908]
   [0.36072907 0.71973264 0.8337182 ]
   [0.6402865  0.9730691  0.24724995]
   [0.5592682  0.56819195 0.87572896]
   [0.612

[[[[0.38479933 0.68800974 0.59960896]
   [0.3537888  0.7160559  0.59479606]
   [0.3588443  0.66044897 0.6475247 ]
   [0.34876636 0.7494658  0.72217333]
   [0.35950765 0.62461644 0.5868825 ]
   [0.4766761  0.8344322  0.9108362 ]
   [0.4941681  0.57887465 0.68840915]
   [0.6759603  0.94736266 0.5745379 ]
   [0.7076789  0.5614876  0.8465705 ]
   [0.6139334  0.96932167 0.43102464]
   [0.55911773 0.53534883 0.8079042 ]
   [0.84201235 0.8470249  0.85888773]
   [0.8414526  0.665276   0.83312446]
   [0.86057645 0.95561385 0.03276913]
   [0.82926124 0.50989276 0.0407564 ]
   [0.8634714  0.6959786  0.01396983]
   [0.85814846 0.79191047 0.02291824]]]]
[[[[0.38479933 0.68800974 0.59960896]
   [0.3537888  0.7160559  0.59479606]
   [0.3588443  0.66044897 0.6475247 ]
   [0.34876636 0.7494658  0.72217333]
   [0.35950765 0.62461644 0.5868825 ]
   [0.4766761  0.8344322  0.9108362 ]
   [0.4941681  0.57887465 0.68840915]
   [0.6759603  0.94736266 0.5745379 ]
   [0.7076789  0.5614876  0.8465705 ]
   [0.613

[[[[0.4494434  0.8446042  0.618366  ]
   [0.43033153 0.87087387 0.6791074 ]
   [0.42552173 0.8243728  0.5933309 ]
   [0.44046208 0.90001994 0.6344471 ]
   [0.42948323 0.790963   0.70676905]
   [0.5783667  0.93072593 0.8893403 ]
   [0.5092849  0.73293793 0.84569585]
   [0.7354488  0.9526145  0.7459916 ]
   [0.57393354 0.61439204 0.8589163 ]
   [0.73905814 0.8789303  0.62698555]
   [0.4826137  0.66868466 0.56042916]
   [0.84282124 0.82390505 0.8078431 ]
   [0.8206925  0.68197566 0.73882294]
   [0.86167175 0.9294676  0.01379141]
   [0.8601283  0.66701996 0.02938664]
   [0.84717506 0.5849417  0.00770691]
   [1.0134116  0.77577645 0.00272166]]]]
[[[[0.4552143  0.863707   0.6613661 ]
   [0.43433666 0.8882009  0.47728318]
   [0.42994207 0.84384596 0.44671765]
   [0.4463381  0.9158813  0.7156531 ]
   [0.43343267 0.8123256  0.6071682 ]
   [0.5900267  0.93974    0.8192915 ]
   [0.50872767 0.7555266  0.8876369 ]
   [0.7451571  0.95806855 0.66662836]
   [0.514894   0.624848   0.8687863 ]
   [0.762

[[[[0.45483416 0.72504276 0.5898403 ]
   [0.4338479  0.74369776 0.56075   ]
   [0.4354379  0.7032608  0.37941712]
   [0.43410575 0.77735    0.6176705 ]
   [0.44573712 0.6733286  0.6803037 ]
   [0.4998406  0.85820764 0.60668886]
   [0.59015644 0.66501707 0.7590803 ]
   [0.44760525 0.97699296 0.33843055]
   [0.7330941  0.64211315 0.71801174]
   [0.30311063 0.97539496 0.37115377]
   [0.8351817  0.5914932  0.4704458 ]
   [0.84326375 0.9186829  0.7669464 ]
   [0.8466625  0.76035064 0.7896639 ]
   [0.9879296  0.9797649  0.05157538]
   [0.85840034 0.6817926  0.01833746]
   [1.0199596  0.97857314 0.04258075]
   [1.0065374  0.7699425  0.01054013]]]]
[[[[0.45189792 0.7201786  0.54311836]
   [0.43033636 0.7405468  0.7335327 ]
   [0.42831555 0.70089996 0.7000203 ]
   [0.43509474 0.7718029  0.6292349 ]
   [0.43568587 0.668471   0.4372083 ]
   [0.5067033  0.84703135 0.70535934]
   [0.579112   0.6516056  0.8595652 ]
   [0.47084454 0.9770685  0.3464765 ]
   [0.7165331  0.63367355 0.79039025]
   [0.339

[[[[0.42189455 0.7498705  0.40241855]
   [0.40073973 0.77038723 0.6798698 ]
   [0.40178552 0.728085   0.6295165 ]
   [0.404021   0.80126244 0.6061321 ]
   [0.40807435 0.6963804  0.6881007 ]
   [0.513824   0.86665833 0.7520864 ]
   [0.535797   0.65450156 0.8641369 ]
   [0.58561236 0.97662425 0.44549322]
   [0.6868132  0.62736017 0.6148894 ]
   [0.5882188  0.9836155  0.04844591]
   [0.7998092  0.6351832  0.42569643]
   [0.84375286 0.8680005  0.7626062 ]
   [0.8421183  0.7137652  0.7284117 ]
   [0.8703916  0.93586767 0.01434651]
   [0.85452014 0.6529533  0.05136653]
   [0.8494985  0.6490987  0.05285043]
   [0.85196155 0.64556706 0.06925338]]]]
[[[[0.42206377 0.744532   0.5730604 ]
   [0.40031365 0.7649582  0.51048875]
   [0.4007228  0.72395724 0.64811075]
   [0.40430284 0.79523695 0.55681014]
   [0.40756592 0.6920627  0.5814066 ]
   [0.5127057  0.8617315  0.80465114]
   [0.5376626  0.6490906  0.8744408 ]
   [0.5827798  0.97414684 0.6698451 ]
   [0.6827509  0.62806934 0.48256662]
   [0.589

[[[[0.44683278 0.6005429  0.6888811 ]
   [0.4276757  0.621027   0.6696197 ]
   [0.42615914 0.58299065 0.7412796 ]
   [0.4372273  0.6438693  0.62996686]
   [0.43304068 0.55599177 0.8060756 ]
   [0.54477483 0.69522214 0.8687168 ]
   [0.5368614  0.5002237  0.8200374 ]
   [0.6978814  0.7405603  0.8897534 ]
   [0.66480273 0.4387376  0.856936  ]
   [0.80487466 0.74653244 0.5426283 ]
   [0.7022927  0.47991344 0.6218525 ]
   [0.84422255 0.6589603  0.8362375 ]
   [0.8396976  0.5178004  0.84203184]
   [0.8625208  0.7521208  0.02508317]
   [0.8509738  0.46263167 0.03377957]
   [0.8506641  0.74161816 0.02447367]
   [0.83576703 0.47307718 0.01143965]]]]
[[[[0.43659344 0.5766173  0.3662146 ]
   [0.41916037 0.5952548  0.55424315]
   [0.41499573 0.5575106  0.7259016 ]
   [0.42996326 0.6163621  0.7868161 ]
   [0.42473415 0.5277478  0.7060317 ]
   [0.5388617  0.6614726  0.9101455 ]
   [0.5195726  0.4716738  0.85073245]
   [0.6976867  0.72023565 0.69406164]
   [0.63068634 0.39149258 0.7638028 ]
   [0.815

[[[[0.45353377 0.602585   0.6979333 ]
   [0.43428266 0.6189672  0.62190384]
   [0.43633264 0.5826494  0.5479742 ]
   [0.44029772 0.64224654 0.6712795 ]
   [0.44521153 0.55941194 0.75346744]
   [0.53605556 0.6964035  0.740574  ]
   [0.53587407 0.5212161  0.8364981 ]
   [0.6435349  0.79892755 0.55458903]
   [0.6382947  0.44364065 0.72033167]
   [0.5856613  0.8380243  0.35304067]
   [0.66517735 0.46730477 0.45865622]
   [0.82772946 0.6721899  0.80249196]
   [0.82338065 0.5337091  0.78078866]
   [0.85881776 0.8488314  0.11025623]
   [0.84724987 0.46848506 0.14998536]
   [0.858532   0.6640094  0.04261669]
   [0.85353845 0.6214904  0.0445489 ]]]]
[[[[0.466082   0.580588   0.6420238 ]
   [0.44462818 0.5976283  0.80207217]
   [0.4466813  0.5609788  0.620574  ]
   [0.44734693 0.6221222  0.79439366]
   [0.45341784 0.5386116  0.70742023]
   [0.5318563  0.6843161  0.7710629 ]
   [0.54636794 0.5020279  0.7361529 ]
   [0.6715629  0.7671934  0.7870619 ]
   [0.64539605 0.433193   0.83702844]
   [0.804

[[[[0.46615162 0.622089   0.6075773 ]
   [0.4473087  0.640994   0.52004784]
   [0.44891474 0.6047496  0.6714176 ]
   [0.45480695 0.6663045  0.7003673 ]
   [0.45906538 0.57967985 0.6853502 ]
   [0.56316495 0.7026155  0.7930674 ]
   [0.5268036  0.5317362  0.75655067]
   [0.6853927  0.7793813  0.7366755 ]
   [0.6220588  0.44529903 0.76999104]
   [0.6294094  0.79182845 0.29762542]
   [0.7006252  0.45232135 0.4322825 ]
   [0.83454424 0.64434415 0.78004265]
   [0.82376146 0.5235831  0.6425155 ]
   [0.85979784 0.8930527  0.02770708]
   [0.8528491  0.4642461  0.03661386]
   [0.8569401  0.9467655  0.02665286]
   [0.8350624  0.46332934 0.01290326]]]]
[[[[0.45687154 0.59503233 0.50216675]
   [0.43671998 0.6118125  0.48096135]
   [0.4378111  0.5769219  0.4897397 ]
   [0.44427034 0.6357221  0.69271934]
   [0.44691873 0.5527722  0.73403406]
   [0.5439529  0.6958824  0.7927807 ]
   [0.5450985  0.5085093  0.76961327]
   [0.656178   0.7633809  0.6367612 ]
   [0.6687303  0.43935603 0.63071704]
   [0.740

[[[[0.48469827 0.5586427  0.54780567]
   [0.46562764 0.5733266  0.5737505 ]
   [0.4676992  0.5396885  0.5520596 ]
   [0.46795353 0.5967346  0.68137646]
   [0.47711232 0.5159651  0.6233642 ]
   [0.54631853 0.6702449  0.83478284]
   [0.58599186 0.48936906 0.92781913]
   [0.6891081  0.76553726 0.9083639 ]
   [0.73027396 0.4930556  0.6420144 ]
   [0.8446223  0.85839486 0.5113736 ]
   [0.72567004 0.5302996  0.5841533 ]
   [0.83461857 0.70001704 0.8202847 ]
   [0.8452614  0.57249314 0.7754476 ]
   [0.8695005  0.8636127  0.06388991]
   [0.8446984  0.49996662 0.05511442]
   [0.8639593  0.8591857  0.16060236]
   [0.8059989  0.5328198  0.03264768]]]]
[[[[0.4701938  0.566326   0.55234987]
   [0.45018417 0.5836728  0.66984236]
   [0.45076787 0.54794055 0.5065489 ]
   [0.4575504  0.6047891  0.5289335 ]
   [0.46477902 0.5222058  0.81520504]
   [0.541543   0.67567796 0.829703  ]
   [0.5719966  0.48869723 0.9348752 ]
   [0.69228894 0.768367   0.8974365 ]
   [0.705586   0.47584406 0.78278637]
   [0.842

[[[[0.47900495 0.58626515 0.742615  ]
   [0.45660132 0.60583764 0.50176066]
   [0.45778102 0.5658335  0.7310951 ]
   [0.45792025 0.6284965  0.80634916]
   [0.46142477 0.54033047 0.8386116 ]
   [0.55068195 0.68974525 0.8169763 ]
   [0.5691916  0.4977085  0.86822426]
   [0.69957596 0.7735591  0.9016179 ]
   [0.7164057  0.45655927 0.7631579 ]
   [0.8502592  0.8616577  0.742772  ]
   [0.8490343  0.43154055 0.6755669 ]
   [0.84476155 0.6911313  0.81059575]
   [0.8489664  0.5583665  0.74951017]
   [0.86758    0.86175275 0.02280263]
   [0.8599143  0.44016755 0.05453024]
   [0.86719364 0.8575193  0.07172424]
   [0.8732493  0.4301651  0.1208128 ]]]]
[[[[0.47844785 0.5870965  0.72771806]
   [0.45591864 0.60787475 0.5864568 ]
   [0.4569075  0.56797135 0.7172245 ]
   [0.45593607 0.6319288  0.78929496]
   [0.45746005 0.5434159  0.7568426 ]
   [0.548322   0.69358665 0.85494244]
   [0.5569015  0.4977632  0.86958766]
   [0.6983753  0.7745279  0.9096178 ]
   [0.7177227  0.45444864 0.8128666 ]
   [0.850

[[[[0.34021038 0.78168625 0.67704403]
   [0.31787232 0.80855894 0.8115212 ]
   [0.31598234 0.7536661  0.71289384]
   [0.33701253 0.8310093  0.84327334]
   [0.33537063 0.7069516  0.788362  ]
   [0.4932256  0.9072586  0.86105525]
   [0.47092664 0.64421344 0.89557695]
   [0.6447874  0.9872318  0.23138528]
   [0.6602013  0.5832512  0.79227465]
   [0.8278565  0.9352173  0.05267904]
   [0.83571136 0.55001736 0.36313057]
   [0.84776    0.88642895 0.65238583]
   [0.8478928  0.7051587  0.7751572 ]
   [0.9988665  0.9650485  0.00932384]
   [0.8651821  0.5645303  0.0190206 ]
   [0.8568248  0.93401575 0.02751731]
   [0.8593695  0.9144487  0.01796517]]]]
[[[[0.3341796  0.7926603  0.7314464 ]
   [0.3080359  0.82027626 0.7866556 ]
   [0.30902296 0.76337236 0.6515942 ]
   [0.3278796  0.84852713 0.7476762 ]
   [0.33053613 0.7208646  0.7107494 ]
   [0.4837273  0.93622094 0.83924496]
   [0.46987045 0.6557132  0.8229207 ]
   [0.6167397  0.9858191  0.10368893]
   [0.6661294  0.6014939  0.7832927 ]
   [0.798

[[[[0.14137633 0.7919402  0.19800784]
   [0.11262182 0.82439774 0.10676515]
   [0.11554421 0.75910276 0.15834664]
   [0.1062226  0.8725172  0.1862594 ]
   [0.12138546 0.6843417  0.27897894]
   [0.29647833 0.9900669  0.53055644]
   [0.3185162  0.5507495  0.6837409 ]
   [0.61517435 0.9813819  0.0990439 ]
   [0.6450268  0.40069622 0.83174616]
   [0.7507446  0.9658761  0.07636244]
   [0.8616573  0.33452722 0.13070472]
   [0.86879665 0.94789326 0.46437246]
   [0.8642052  0.6794745  0.43886036]
   [0.85206294 0.9405486  0.04864669]
   [0.85477126 0.6008633  0.04916972]
   [0.8477372  0.847886   0.0981988 ]
   [0.85139865 0.75735986 0.09914811]]]]
[[[[0.14188844 0.7630295  0.06453104]
   [0.11426466 0.85225594 0.06163596]
   [0.12485784 0.71413183 0.02297405]
   [0.10284816 0.8942302  0.15055422]
   [0.11183478 0.62868756 0.10923693]
   [0.22006844 0.98804647 0.57110226]
   [0.2992043  0.46386456 0.5687133 ]
   [0.624676   0.9758382  0.16033769]
   [0.68977994 0.27524826 0.5573501 ]
   [0.823

[[[[0.60846907 0.463942   0.5702851 ]
   [0.5697061  0.5136413  0.64661205]
   [0.5571806  0.4228255  0.55019987]
   [0.5885733  0.5604514  0.5439707 ]
   [0.5617942  0.36318377 0.6750862 ]
   [0.8133999  0.6391576  0.5497477 ]
   [0.76682174 0.23134577 0.71392894]
   [0.9964245  0.6839876  0.02591385]
   [0.8713365  0.09718694 0.07035985]
   [1.0010082  0.54158694 0.03204228]
   [0.87233585 0.07824832 0.01687798]
   [1.0312619  0.5475712  0.05156599]
   [0.9792412  0.19797847 0.02406401]
   [0.8555208  0.66143423 0.02405378]
   [0.98966795 0.37882465 0.05508176]
   [0.75110567 0.48184112 0.02063   ]
   [0.9815137  0.5815179  0.00510576]]]]
[[[[ 0.6131734   0.45968077  0.6623295 ]
   [ 0.57272035  0.51112616  0.69072926]
   [ 0.5627841   0.41967183  0.41601261]
   [ 0.5934692   0.55381763  0.65877664]
   [ 0.56804216  0.36073074  0.6205013 ]
   [ 0.80890405  0.6374149   0.55024827]
   [ 0.771914    0.21849094  0.69760287]
   [ 0.99511784  0.68329334  0.03860491]
   [ 0.86921763  0.0930

[[[[0.4629097  0.7647868  0.02693666]
   [0.3814716  0.8195668  0.05295064]
   [0.37882173 0.72890615 0.03431427]
   [0.3697219  0.8802483  0.05538163]
   [0.35031337 0.6515488  0.02867959]
   [0.45447218 0.9040408  0.04326274]
   [0.45990968 0.55763614 0.0384629 ]
   [0.7924181  0.8295307  0.06504495]
   [0.6195193  0.20162411 0.08973079]
   [0.819156   0.734076   0.0562817 ]
   [0.7431048  0.41264874 0.01123027]
   [0.8530316  0.8307875  0.15311861]
   [0.7499967  0.46070346 0.04106293]
   [0.6627414  0.1836664  0.14834067]
   [0.67084193 0.20146964 0.22502688]
   [0.7858799  0.51335275 0.06561542]
   [0.70310986 0.32871333 0.01581061]]]]
[[[[0.42092687 0.6819163  0.07841248]
   [0.2860883  0.70231    0.18365604]
   [0.26844794 0.5675714  0.23697925]
   [0.2869076  0.8856034  0.14577933]
   [0.3207374  0.5373917  0.08661298]
   [0.76366955 0.98598063 0.1887148 ]
   [0.70515627 0.225772   0.25794268]
   [0.7962152  0.868067   0.05505405]
   [0.6335757  0.18254824 0.07298723]
   [0.788

[[[[0.582803   0.48122957 0.6140681 ]
   [0.5207932  0.5393397  0.73152745]
   [0.52154756 0.4275961  0.7554206 ]
   [0.5238264  0.60544723 0.77544284]
   [0.5229441  0.35637152 0.5597712 ]
   [0.750637   0.69459385 0.7544795 ]
   [0.7207723  0.22748876 0.7954691 ]
   [0.9689754  0.8660949  0.1021587 ]
   [0.8701699  0.10082021 0.05273664]
   [0.86841655 0.65460324 0.0207741 ]
   [0.14854714 0.33166793 0.04655725]
   [1.030015   0.6192381  0.08756674]
   [0.9130327  0.2307695  0.03733144]
   [0.7862047  0.7217275  0.03002058]
   [0.9873392  0.39885715 0.06861318]
   [0.72855216 0.5874247  0.02919681]
   [0.708085   0.4930988  0.0548674 ]]]]
[[[[ 0.58793724  0.4870513   0.55062664]
   [ 0.5224304   0.5481352   0.5994022 ]
   [ 0.5208368   0.43535125  0.7181267 ]
   [ 0.52323633  0.6116117   0.67067266]
   [ 0.5183692   0.35675374  0.49645936]
   [ 0.74689823  0.6988972   0.7459641 ]
   [ 0.71739024  0.22956432  0.67116797]
   [ 0.97787404  0.8903477   0.09034664]
   [ 0.8734843   0.0888

### Keypoints

In [7]:
def draw_keypoints(frame, keypoints, confidence_threshold):
    y, x, c = frame.shape
    shaped = np.squeeze(np.multiply(keypoints, [y, x, 1]))
    
    for kp in shaped:
        ky, kx, kp_conf = kp
        if kp_conf > confidence_threshold:
            cv2.circle(frame, (int(kx), int(ky)), 4, (0, 255, 0), -1)

### Edges

In [8]:
EDGES = {
    (0, 1): 'm',
    (0, 2): 'c',
    (1, 3): 'm',
    (2, 4): 'c',
    (0, 5): 'm',
    (0, 6): 'c',
    (5, 7): 'm',
    (7, 9): 'm',
    (6, 8): 'c',
    (8, 10): 'c',
    (5, 6): 'y',
    (5, 11): 'm',
    (6, 12): 'c',
    (11, 12): 'y',
    (11, 13): 'm',
    (13, 15): 'm',
    (12, 14): 'c',
    (14, 16): 'c'
}

In [12]:
def draw_edges(frame, keypoints, edges, confidence_threhold):
    y, x, c = frame.shape
    shaped = np.squeeze(np.multiply(keypoints, [y, x, 1]))
    
    for edge, color in edges.items():
        p1, p2 = edge
        y1, x1, c1 = shaped[p1]
        y2, x2, c2 = shaped[p2]
        
        if (c1 > confidence_threhold) & (c2 > confidence_threhold):
            cv2.line(frame, (int(x1), int(y1)), (int(x2), int(y2)), (0, 0, 255), 2)